import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { getSession } from 'next-auth/react'
import CommentCard from '../src/components/CommentCard'
import CommentInput from '../src/components/CommentInput'
import FeedBackCard from '../src/components/FeedBackCard'
import SubNav from '../src/components/SubNav'
import Button from '../src/styledComponents/Button'
import FeedWrapper from '../src/styledComponents/FeedWrapper'

function feedbackPage({ data, session }) {

    const [addComment, setAddComment] = useState(false)

    const user = session?.user
    
    // Get feedback and comments from get server side Props
    const commentArr = data.data.comments
    const feedbackArr = data.data.feedback[0]

    useEffect(() => {
        console.log(user)
    }, [])


    return (
        <FeedWrapper className='feedback__page' >
            <Head>
                <title>{feedbackArr.feedback_head}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FeedWrapper>
                <SubNav id={feedbackArr.feedback_id} />
            </FeedWrapper>
            <FeedWrapper className='feedback__page__feedback'>
                <FeedBackCard
                    head={feedbackArr.feedback_head}
                    tag={feedbackArr.tag}
                    id={feedbackArr.feedback_id}
                >
                    {feedbackArr.feedback_body}
                </FeedBackCard>
            </FeedWrapper>
            <FeedWrapper className='feedback__page__comments'>
                <FeedWrapper className='feedback__page__comments__head'>
                    <FeedWrapper className='feedback__page__comments__head__text'>
                        Comments
                    </FeedWrapper>
                    <FeedWrapper className='feedback__page__comments__head__btn'>
                        <Button type="primary" click={() => setAddComment(!addComment)} >
                            Add Comment
                        </Button>
                    </FeedWrapper>
                </FeedWrapper>
                <FeedWrapper>
                    {
                        addComment ? (
                            <>
                                <CommentInput id={feedbackArr.feedback_id} setAddComment={setAddComment} />
                            </>
                        ) : null
                    }
                </FeedWrapper>
                <FeedWrapper className='feedback__page__comments__render'>
                    {
                        commentArr?.map((comment, index) => (
                            <CommentCard key={index} >
                                {comment.comment_body}
                            </CommentCard>
                        ))
                    }
                </FeedWrapper>
            </FeedWrapper>
        </FeedWrapper>
    )
}

export async function getServerSideProps(context) {
    const session = await getSession(context)
    
    //Check for auth session
    if(!session){
        return {
            redirect: {
                destination: '/api/auth/signin?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2F',
                permanent: false
            }
        }
    }
    const id = context.query.id

    //Get feedbacks from server
    const res = await fetch(`http://localhost:5000/feedback?id=${id}`)
    const data = await res.json()



    return {
        props: { data, session }
    }
}

export default feedbackPage
