import Head from 'next/head'
import { useEffect } from 'react'
import { useSession, signIn, signOut } from "next-auth/react"
import CategoryCard from '../src/components/CategoryCard'
import FeedBackCard from '../src/components/FeedBackCard'
import LogoCard from '../src/components/LogoCard'
import MainNav from '../src/components/MainNav'
import HomeWrapper from '../src/styledComponents/HomeWrapper'
import Main from '../src/styledComponents/Main'
import Button from '../src/styledComponents/Button'
import LinkAnchor from '../src/components/LinkAnchor'

export default function Home({ data }) {

  const feedbacks = data.data

  const { data: session } = useSession()


  useEffect(() => {
    console.log(session)

  }, [])



  return (
    <HomeWrapper className="home">
      <Head>
        <title>Frontend Mentor | Feedback </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <HomeWrapper className="home__category__section" >
          <HomeWrapper>
            <LogoCard />
          </HomeWrapper>
          <HomeWrapper>
            <CategoryCard />
          </HomeWrapper>
          {session ? null : (
            <HomeWrapper>
              <LinkAnchor route={'/registration'}>
                <Button
                  type="primary"
                >
                  Sign Up
                </Button>
              </LinkAnchor>
            </HomeWrapper>
          )}
          <HomeWrapper>
            <Button
              type="primary"
              click={() => session ? signOut() : signIn()}
            >
              {session ? "Sign Out" : " Sign In"}
            </Button>
          </HomeWrapper>

        </HomeWrapper>
        <HomeWrapper className="home__main" >
          <HomeWrapper>
            <MainNav suggestions={feedbacks.length} />
          </HomeWrapper>
          <HomeWrapper>
            {
              feedbacks.map((feedback, index) => (
                <FeedBackCard head={feedback.feedback_head} tag={feedback.tag} key={index} id={feedback.feedback_id}  >
                  {feedback.feedback_body}
                </FeedBackCard>
              ))
            }
          </HomeWrapper>
        </HomeWrapper>
      </Main>


    </HomeWrapper>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:5000/getFeedbacks')
  const data = await res.json()

  return {
    props: { data }
  }
}